---
language: php

os: linux

version: ~> 1.0

php: ['7.3', '7.4', '8.0']

branches:
  only:
    - master
    - develop
    - wip

env:
  global:
    - XDEBUG_MODE=coverage

jobs:
  fast_finish: true

install: composer install

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
  - vendor/bin/behat -fprogress --strict

after_success:
  - travis_retry ./vendor/bin/php-coveralls
