---
language: php

os: linux

version: ~> 1.0

php: [7.1, 7.2, 7.3]

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - develop
    - wip

jobs:
  fast_finish: true

install: composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/behat -fprogress --strict

after_success:
  - travis_retry ./vendor/bin/php-coveralls
