language: php

php:
  - 5.6

sudo: false

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --prefer-dist --no-interaction --dev

script: vendor/bin/phpunit

matrix:
  fast_finish: true
