---
name: Tests

on:
    push:
        branches: [ master, wip ]
    pull_request:
        branches: [ master ]
    schedule:
        # Every Monday at 00:00:00 UTC.
        # @see https://crontab.cronhub.io/
        -   cron: "0 0 * * 1"

jobs:
    build:
        name: "PHP ${{ matrix.php }}"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["8.3", "8.4", "8.5"]
        steps:
            -   name: "Set up PHP"
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: "${{ matrix.php }}"

            -   name: "Checkout code"
                uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v3 # https://github.com/marketplace/actions/install-composer-dependencies
                with:
                    composer-options: "--no-cache"

            -   name: "Run Tests"
                run: composer check:test

            -   name: "Run Static Analysis"
                run: composer check:static
